### ISSUE TITLE
Apr. 12 Commit Bug: all_pcode is no longer pcode and is a copy of all_vba

### ISSUE THREAD

**Issue by Mudge-0** [CybercentreCanada/assemblyline-service-oletools#16]
I have not determined a proper fix, but noticed after an update of the oletools service that all_vba and all_pcode are now equivalent files and are just the vba. Starting point for bug fix at:

https://github.com/CybercentreCanada/assemblyline-service-oletools/blob/75ac2d0d2e3d89789dfbd049ea23ceeeaa6e49a4/oletools_/oletools_.py#L795-L796

Here are the two calls that produce the files and it can be seen that these calls will produce identical files. the Pcode is not being passed into mraptor.

**Comment by cccs-jh** [comment]
Thank you for flagging this, the wrong variable was being passed in.
